### ISSUE TITLE
pip install mezzanine_polls did not work

### ISSUE THREAD

**Issue by CorrosiveKid** [sebasmagri/mezzanine_polls#1]
'pip install mezzanine_polls' command does not work. (Linux Ubuntu 12.04 LTS)

Returns:

> $ pip install mezzanine_polls
> Downloading/unpacking mezzanine-polls
>  Could not find any downloads that satisfy the requirement mezzanine-polls
> No distributions at all found for mezzanine-polls

**Comment by sebasmagri** [comment]
Hi @CorrosiveKid.

You need to use

```
$ pip install mezzanine-polls
```

To correctly install the module.

**Comment by sebasmagri** [comment]
I'm sorry, just checked and it's not working. Gonna check this out.

**Comment by sebasmagri** [comment]
This should be working now.

Regards,

**Comment by CorrosiveKid** [comment]
Cool!
